# Generated by Django 5.2.1 on 2025-06-26 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomproducts', '0002_product_varients_remove_products_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_Varients',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
