# Generated by Django 5.2.1 on 2025-06-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomproducts', '0006_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
