# Generated by Django 5.2.1 on 2025-07-18 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomproducts', '0008_alter_categories_name_alter_product_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Varients',
            new_name='ProductVarients',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='ecomproducts.product'),
        ),
    ]
