# Generated by Django 5.2.1 on 2025-07-19 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomproducts', '0009_rename_product_varients_productvarients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='createdd_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 19, 5, 43, 59, 757714, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
