# Generated by Django 5.2.1 on 2025-07-19 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomproducts', '0010_product_createdd_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='createdd_at',
            new_name='created_at',
        ),
    ]
