# Generated by Django 5.2.1 on 2025-07-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomproducts', '0011_rename_createdd_at_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
