# Generated by Django 5.2.1 on 2025-07-25 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomproducts', '0014_productvariant_delete_productvarients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='discount',
        ),
    ]
