# Generated by Django 5.2.1 on 2025-07-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomproducts', '0015_remove_productvariant_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='discount',
            field=models.PositiveIntegerField(default=10, editable=False),
        ),
    ]
