# Generated by Django 5.2.1 on 2025-09-14 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomproducts', '0016_productvariant_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(help_text='Unique code for each coupon', max_length=50, unique=True)),
                ('is_valid', models.BooleanField(default=True, help_text='Whether the coupon is active or not')),
                ('description', models.TextField(blank=True, help_text='Optional description for the coupon')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the coupon is created')),
                ('valid_from', models.DateTimeField(help_text='Start date of coupon validity')),
                ('valid_to', models.DateTimeField(help_text='End date for coupon validity')),
                ('minimum_purchase_amount', models.DecimalField(decimal_places=2, help_text='Minimum amount required to apply this coupon', max_digits=10, validators=[django.core.validators.MinValueValidator(1.0, message='minimum purchase amount must be positive')])),
                ('discount_percentage', models.PositiveIntegerField(help_text='Discount for this coupon is between 10 and 80', validators=[django.core.validators.MinValueValidator(10, message='the discount must be greater than 10 percent'), django.core.validators.MaxValueValidator(80, message='the discount must not exeed 80 percent')])),
                ('max_usage_limit', models.PositiveIntegerField(default=0, help_text='Number of times this coupon can use')),
                ('total_usage', models.PositiveIntegerField(default=0, help_text='Number of times this coupon is used')),
            ],
        ),
    ]
