# Generated by Django 5.2.1 on 2025-09-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomproducts', '0017_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='is_valid',
            new_name='is_active',
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.UniqueConstraint(fields=('coupon_code',), name='unique_coupon_code'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('valid_from__lte', models.F('valid_to'))), name='valid_from_before_valid_to'),
        ),
    ]
