# Generated by Django 5.2.1 on 2025-09-16 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomproducts', '0018_rename_is_valid_coupon_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the offer for admin reference', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the offer is active or not')),
                ('description', models.TextField(blank=True, help_text='Optional description for the offer')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the offer is created')),
                ('valid_from', models.DateTimeField(help_text='Start date of offer validity')),
                ('valid_to', models.DateTimeField(help_text='End date for offer validity')),
                ('discount_percentage', models.PositiveIntegerField(help_text='Discount percentage for this offer, between 5 and 70', validators=[django.core.validators.MinValueValidator(5, message='The discount must be at least 5 percent'), django.core.validators.MaxValueValidator(70, message='The discount must not exceed 70 percent')])),
            ],
        ),
    ]
