# Generated by Django 5.2.1 on 2025-10-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomproducts', '0019_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='discount',
            field=models.PositiveIntegerField(blank=True, default=10, editable=False, null=True),
        ),
    ]
