# Generated by Django 5.2.1 on 2025-10-06 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomproducts', '0021_offer_category_offer_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='discount',
        ),
    ]
