# Generated by Django 5.2.1 on 2025-11-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomproducts', '0022_remove_productvariant_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_code',
            field=models.CharField(help_text='Unique code for each coupon (strictly alphanumeric)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='name',
            field=models.CharField(help_text='Name of the offer for admin reference (Only alphanumeric value)', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('product',), name='unique_product_offer'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', False)), fields=('category',), name='unique_category_offer'),
        ),
    ]
