# Generated by Django 5.2.1 on 2025-08-26 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomorders', '0005_orderitem_delivery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='delivery_status',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='variant',
        ),
    ]
