# Generated by Django 5.2.1 on 2025-08-26 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomorders', '0006_remove_orderitem_delivery_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
