# Generated by Django 5.2.1 on 2025-08-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomorders', '0008_orderitem_delivery_status_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('DELAY', 'Delivery taking too long'), ('CHANGED_MIND', 'Changed my mind'), ('FOUND_BETTER', 'Found a better price elsewhere'), ('WRONG_ITEM', 'Ordered wrong item'), ('OTHER', 'Other reason')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='other_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
