# Generated by Django 5.2.1 on 2025-08-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomorders', '0009_orderitem_cancellation_reason_orderitem_other_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned')], default='ACTIVE', max_length=20),
        ),
    ]
