# Generated by Django 5.2.1 on 2025-09-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomorders', '0011_alter_orderitem_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='return_other_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_reason',
            field=models.CharField(blank=True, choices=[('DAMAGED', 'Product was damaged'), ('DEFECTIVE', 'Product was defective'), ('WRONG_ITEM', 'Wrong item delivered'), ('NOT_SATISFIED', 'Not satisfied with the product'), ('OTHER', 'Other reason')], max_length=50, null=True),
        ),
    ]
