# Generated by Django 5.2.1 on 2025-09-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomorders', '0012_orderitem_return_other_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
