# Generated by Django 5.2.1 on 2025-09-19 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomorders', '0014_order_razorpay_payment_id_order_razorpay_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='PENDING', max_length=20)),
                ('reason', models.CharField(blank=True, choices=[('DAMAGED', 'Product was damaged'), ('DEFECTIVE', 'Product was defective'), ('WRONG_ITEM', 'Wrong item delivered'), ('NOT_SATISFIED', 'Not satisfied with the product'), ('OTHER', 'Other reason')], max_length=50, null=True)),
                ('other_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_request', to='ecomorders.orderitem')),
            ],
        ),
    ]
