# Generated by Django 5.2.1 on 2026-01-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomorders', '0015_returnrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='delivery_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('ARRIVED', 'Arrived'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned'), ('RETURN_REQUESTED', 'Return Requested')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned'), ('RETURN_REQUESTED', 'Return Requested')], default='ACTIVE', max_length=20),
        ),
    ]
