# Generated by Django 5.2.1 on 2025-05-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=1234567890, max_length=10),
            preserve_default=False,
        ),
    ]
