# Generated by Django 5.2.1 on 2025-06-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomusers', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
