# Generated by Django 5.2.1 on 2025-07-26 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomusers', '0006_cartproducts_wishlistproducts'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlistproducts',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='wishlistproducts',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wishlistproducts',
            name='variant',
        ),
        migrations.DeleteModel(
            name='CartProducts',
        ),
        migrations.DeleteModel(
            name='WishlistProducts',
        ),
    ]
