# Generated by Django 5.2.1 on 2025-07-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomusers', '0010_cartproducts'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='useraddress',
            constraint=models.UniqueConstraint(fields=('user', 'addressline_1', 'addressline_2', 'city', 'state', 'nation', 'postal_code'), name='unique_address_per_user'),
        ),
    ]
