# Generated by Django 5.2.1 on 2025-07-31 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomusers', '0011_useraddress_unique_address_per_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='useraddress',
            name='unique_address_per_user',
        ),
    ]
