# Generated by Django 5.2.1 on 2025-10-14 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomusers', '0016_wallettransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallettransaction',
            old_name='Wallet',
            new_name='wallet',
        ),
    ]
