# Generated by Django 5.2.1 on 2025-12-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomusers', '0017_rename_wallet_wallettransaction_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproducts',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
