# Generated by Django 5.2.1 on 2026-01-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomusers', '0018_alter_cartproducts_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='transaction_source',
            field=models.CharField(blank=True, choices=[('WALLET', 'Wallet Payment'), ('REFERRAL', 'Referral Reward'), ('CANCEL', 'Cancel Refund'), ('RETURN', 'Return Refund')], max_length=15, null=True),
        ),
    ]
