# Generated by Django 5.2.1 on 2026-01-24 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomorders', '0015_returnrequest'),
        ('ecomusers', '0019_wallettransaction_transaction_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecomorders.order'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecomorders.orderitem'),
        ),
    ]
