# Generated by Django 5.2.1 on 2026-02-26 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomorders', '0017_order_coupon_discount_order_offer_discount'),
        ('ecomusers', '0020_wallettransaction_order_wallettransaction_order_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('ACCOUNT', 'Account Issues'), ('PROFILE', 'Profile Issues'), ('ORDER', 'Order Issues'), ('PAYMENT', 'Payment Issues'), ('REFUND', 'Refund Issues'), ('DELIVERY', 'Delivery Issues'), ('OTHERS', 'Any Other Concerns')], default='ACCOUNT', max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('admin_reply', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecomorders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
